spring:
  datasource:
    url: jdbc:h2:mem:gs
    username: test
    password: test
    initialization-mode: always
  h2.console.enabled: true
key:
  url: "http://rss.cnn.com/rss/cnn_topstories.rss"
  interval: "0 * * ? * *"


